Update Android.bp
Cause below error. To fix this few lines has to be commented.
error: vendor/superior/build/soong/Android.bp:24:8: module "generated_kernel_includes": cmd: unknown variable '$(PATH_OVERRIDE_SOONG)'